#!/bin/bash

# The MIT License (MIT)
# 
# Copyright (c) 2014 Stephen Parker
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


# apt-get install imagemagick
echo 
echo 
echo "1Page Gallery build script by Stephen Parker"
echo "Released under the MIT license. See LICENSE."
echo 

# Make sure zip exists, if not exit now
echo "Searching for high resolution image zip file..."
FOUND=`find . -name *.zip | wc -l`
if [ $FOUND -lt 1 ]; then
	echo 
	echo "Error: Please upload a zip file containing your high resolution images to this directory and retry."
	echo 
	exit 1;
fi

# Make necessary directories
echo "Creating full scale image directory..."
mkdir -p images
echo "Creating thumbnail image directory..."
mkdir -p thumbs

# Unzip zip of all images
echo "Unzipping images..."
unzip *.zip -d images/

cd images

# Resize images
echo "Resizing full scale images for the web..."
for file in *.{JPG,jpg,JPEG,jpeg}; do
   if [[ -f "$file" ]]; then
      convert -resize 700 "$file" tmp_"$file"
      rm "$file"
      mv tmp_"$file" "$file"
   fi
done

# Make thumbnails
echo "Creating thumbnail images..."
for file in *.{JPG,jpg,JPEG,jpeg}; do
   if [[ -f "$file" ]]; then
      convert -resize 80 "$file" ../thumbs/"$file"
   fi
done

